(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e,g="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},h;if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var l;a:{var m={P:!0},n={};try{n.__proto__=m;l=n.P;break a}catch(a){}l=!1}h=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var p=h,q=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},r=q(this);var t="abort canplay canplaythrough durationchange emptied ended error loadeddata loadedmetadata loadstart pause play playing progress ratechange seeked seeking stalled suspend timeupdate volumechange waiting".split(" "),u={".avi":1,".m4v":1,".mp4":1,".mpeg":1,".mpg":1,".ogg":1,".ogv":1,".qt":1,".webm":1,".wmv":1};var v=function(a,b){window.setTimeout(a,b)};var w=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)},x=function(a,b){var c=function(d){a.removeEventListener("playing",c);b(d)};a.addEventListener("playing",c)};var y=function(){this.H=""};y.prototype.toString=function(){return"SafeScript{"+this.H+"}"};y.prototype.b=function(a){this.H=a};(new y).b("");var z=function(){this.J=""};z.prototype.toString=function(){return"SafeStyle{"+this.J+"}"};z.prototype.b=function(a){this.J=a};(new z).b("");var A=function(){this.I=""};A.prototype.toString=function(){return"SafeStyleSheet{"+this.I+"}"};A.prototype.b=function(a){this.I=a};(new A).b("");var B=function(){this.G=""};B.prototype.toString=function(){return"SafeHtml{"+this.G+"}"};B.prototype.b=function(a){this.G=a};(new B).b("<!DOCTYPE html>");(new B).b("");(new B).b("<br>");var D=function(a){if(!a.gwdIsLoaded()){var b=C(a);b?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad()}},E=function(a){if(!a.gwdIsActive()){var b=C(a);b?b.gwdIsActive()&&a.gwdActivate():a.gwdActivate()}},F=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},C=function(a){if(F(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&F(a))return a;return null},G=function(a){for(var b=[];a;)b.unshift(a),a=a.parentNode;return b},H=function(a,b,c){a.hasAttribute(b)?(a=a.getAttribute(b),
c.setAttribute(b,a)):c.removeAttribute(b)};var I={M:"fullscreenchange",N:"mozfullscreenchange",O:"webkitfullscreenchange"},J={M:"fullscreenElement",N:"mozFullScreenElement",O:"webkitFullscreenElement"},K=function(a){for(var b,c=Object.keys(J),d=0;d<c.length&&(b=a[J[c[d]]],void 0===b);d++);return b||null},L=function(a){var b=document;this.l="has-fullscreen-gwd-video";this.c=b;this.h=a;this.A=this.T.bind(this)};
L.prototype.T=function(){var a=K(this.c);if(a)if(this.h==a){var b=this.c;for(a=this.h;a&&a!=b;a=a.parentNode)a.classList.add(this.l)}else if(a.classList.contains(this.l)){b=G(this.h);a=G(a);for(var c=0,d=b[0],f=a[0],k=null;d&&f&&d==f;)k=d,c++,d=b[c],f=a[c];M(this,k)}else M(this);else M(this)};var M=function(a,b){b=(void 0===b?null:b)||a.c;for(var c=a.h;c&&c!=b;c=c.parentNode)c.classList.remove(a.l)};
L.prototype.install=function(){for(var a=Object.keys(I),b=0;b<a.length;b++)this.c.addEventListener(I[a[b]],this.A)};var N=Object.keys(HTMLMediaElement.prototype).concat(Object.keys(HTMLVideoElement.prototype)).concat(["sources"]),O=function(){var a=HTMLElement.call(this)||this;a.a=a.ownerDocument.createElement("video");a.a.setAttribute("webkit-playsinline","");a.a.setAttribute("playsinline","");a.a.setAttribute("x-webkit-airplay","allow");a.w=function(b){w(b.type,a,b.detail)};a.L=a.R.bind(a);a.B=new L(a.a);a.f=!1;a.g=null;a.j=null;a.interactiveVideoComponents=[];a.S=function(){for(var b=0;b<a.interactiveVideoComponents.length;b++)a.interactiveVideoComponents[b].handleVideoTimeUpdate()};
a.K=function(){a.g||(a.g=window.setInterval(a.S,33))};a.i=function(){a.g&&(window.clearInterval(a.g),a.g=null)};a.F=null;a.D=null;a.u=function(){if(a.parentElement){var b=a.getBoundingClientRect();if(b.width!=a.F||b.height!=a.D)for(a.F=b.width,a.D=b.height,b=0;b<a.interactiveVideoComponents.length;b++)a.interactiveVideoComponents[b].resizeHandlerNeeded&&a.interactiveVideoComponents[b].resize()}};a.U=function(){a.j||(a.j=window.setInterval(a.u,250))};a.V=function(){a.j&&window.clearInterval(a.j)};
a.o=!1;a.m=!1;a.C=!1;a.v=1;a.s=!1;return a},P=HTMLElement;O.prototype=g(P.prototype);O.prototype.constructor=O;if(p)p(O,P);else for(var Q in P)if("prototype"!=Q)if(Object.defineProperties){var R=Object.getOwnPropertyDescriptor(P,Q);R&&Object.defineProperty(O,Q,R)}else O[Q]=P[Q];e=O.prototype;
e.connectedCallback=function(){var a=this;if(!this.C){for(var b=0;b<this.children.length;b++){var c=this.children[b];if(c.classList.contains("intermediate-element")){this.removeChild(c);break}}this.f=this.muted&&-1!=(window.navigator.userAgent||"").indexOf("Android");for(b=0;b<this.children.length;b++)if(c=this.children[b],c.classList.contains("intermediate-element")){this.removeChild(c);break}b=document.createElement("div");b.classList.add("intermediate-element");b.appendChild(this.a);this.appendChild(b);
this.C=!0}D(this);E(this);this.f&&x(this.a,function(){a.f&&(a.a.volume=0)});this.a.addEventListener("volumechange",this.L,!1);for(b=0;b<t.length;b++)this.a.addEventListener(t[b],this.w,!1);this.B.install();this.a.addEventListener("play",this.K,!1);this.a.addEventListener("pause",this.i,!1);this.a.addEventListener("ended",this.i,!1)};
e.disconnectedCallback=function(){for(var a=this.B,b=Object.keys(I),c=0;c<b.length;c++)a.c.removeEventListener(I[b[c]],a.A);b=K(a.c);a.h==b&&M(a);this.f&&(this.a.volume=1);this.a.removeEventListener("volumechange",this.L,!1);for(a=0;a<t.length;a++)this.a.removeEventListener(t[a],this.w,!1);this.i();this.a.removeEventListener("play",this.K,!1);this.a.removeEventListener("pause",this.i,!1);this.a.removeEventListener("ended",this.i,!1)};
e.setResizeObserver=function(){for(var a=!1,b=0;b<this.interactiveVideoComponents.length;b++)if(this.interactiveVideoComponents[b].resizeHandlerNeeded){a=!0;break}a?(this.U(),window.addEventListener("resize",this.u,!1)):(this.V(),window.removeEventListener("resize",this.u,!1))};
e.attributeChangedCallback=function(a){var b=this;if("sources"==a){if(this.o){var c=this.a.paused,d=this.muted;S(this);this.a.load();v(function(){b.muted=d;c?b.pause():b.play()},0)}}else"muted"==a&&(this.a.muted=this.muted);H(this,a,this.a)};e.gwdActivate=function(){var a=this;this.autoplay&&this.a.paused&&v(function(){a.play()},200);this.m=!0};e.gwdDeactivate=function(){this.hasAttribute("resumable")||this.seek(0);this.pause();this.m=!1};e.gwdIsActive=function(){return this.m};
e.gwdLoad=function(){S(this);this.o=!0;w("ready",this)};e.gwdIsLoaded=function(){return this.o};e.play=function(){this.a.play()};e.pause=function(){this.a.pause()};e.mute=function(){this.f&&(this.a.volume=1);this.f=!1;this.muted=!this.muted};e.replay=function(){this.seek(0);this.play()};e.seek=function(a){this.currentTime!=a&&(this.currentTime=a)};e.R=function(){0==this.s&&1==this.muted&&0==this.v&&(this.a.volume=1,this.muted=!1);this.v=this.a.volume;this.s=this.muted};
e.setVolume=function(a){this.muted=0<a?!1:!0;this.a.volume=a/100;this.v=this.a.volume;this.s=this.muted};e.setSources=function(a){this.setAttribute("sources",a)};
var S=function(a){var b=a.getAttribute("sources");b=T(b);for(var c=a.a.children,d=c.length-1;0<=d;d--){var f=c[d];"source"==f.tagName.toLowerCase()&&a.a.removeChild(f)}for(c=0;c<b.length;c++)d=document.createElement("source"),f=b[c],f=f.trim(),f=window.Enabler?window.Enabler.getUrl(f):f,d.src=f,a.a.appendChild(d)},T=function(a){var b=[];if(!a)return b;a=a.split(",").map(function(U){return U.trim()});for(var c="",d=0;d<a.length;d++){var f=a[d];c+=f;var k=f.lastIndexOf(".");-1!=k?u[f.substring(k).toLowerCase()]?
(b.push(c),c=""):c+=",":c+=","}c&&b.push(c.substring(0,c.length-1));return b};
r.Object.defineProperties(O.prototype,{nativeElement:{configurable:!0,enumerable:!0,get:function(){return this.a}},autoplay:{configurable:!0,enumerable:!0,get:function(){return this.a.autoplay},set:function(a){a?this.setAttribute("autoplay",""):this.removeAttribute("autoplay")}},loop:{configurable:!0,enumerable:!0,get:function(){return this.a.loop},set:function(a){a?this.setAttribute("loop",""):this.removeAttribute("loop")}},muted:{configurable:!0,enumerable:!0,get:function(){return this.hasAttribute("muted")},
set:function(a){a?this.setAttribute("muted",""):this.removeAttribute("muted")}},controls:{configurable:!0,enumerable:!0,get:function(){return this.a.controls},set:function(a){a?this.setAttribute("controls",""):this.removeAttribute("controls")}},poster:{configurable:!0,enumerable:!0,get:function(){return this.a.poster},set:function(a){a?this.setAttribute("poster",a):this.removeAttribute("poster")}},paused:{configurable:!0,enumerable:!0,get:function(){return this.a.paused}},volume:{configurable:!0,
enumerable:!0,get:function(){return this.a.volume},set:function(a){this.a.volume=a}},currentTime:{configurable:!0,enumerable:!0,get:function(){return this.a.currentTime},set:function(a){this.a.currentTime=a}},duration:{configurable:!0,enumerable:!0,get:function(){return this.a.duration}},width:{configurable:!0,enumerable:!0,get:function(){return this.a.width},set:function(a){a&&(this.a.width=a)}},height:{configurable:!0,enumerable:!0,get:function(){return this.a.height},set:function(a){a&&(this.a.height=
a)}},videoWidth:{configurable:!0,enumerable:!0,get:function(){return this.a.videoWidth}},videoHeight:{configurable:!0,enumerable:!0,get:function(){return this.a.videoHeight}}});r.Object.defineProperties(O,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return N}}});customElements.define("gwd-video",O);}).call(this);
